# Generated by Django 2.1 on 2020-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='加精'),
        ),
    ]
