# Generated by Django 2.1 on 2020-05-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('body', models.CharField(max_length=256, verbose_name='评论')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('belongto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.Blogs', verbose_name='从属')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_time'],
            },
        ),
    ]
