# Generated by Django 2.1 on 2020-05-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '10005_auto_20200519_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='belongtovlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Vlogs', verbose_name='从属vlog'),
        ),
    ]
