# Generated by Django 2.1 on 2020-05-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '10004_comments_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blod_img', verbose_name='vlog配图')),
                ('body', models.TextField(verbose_name='正文')),
                ('abstract', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('visiting', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyed_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'vlog',
                'verbose_name_plural': 'vlog',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='belongto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blogs', verbose_name='从属'),
        ),
    ]
