# Generated by Django 2.1 on 2020-05-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '10003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(max_length=128, null=True, verbose_name='邮件'),
        ),
    ]
